const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('projectA', {
  chooseFolders: () => ipcRenderer.invoke('library:choose-folders'),
  scan: () => ipcRenderer.invoke('library:scan'),
  clearLibrary: () => ipcRenderer.invoke('library:clear'),
  removeFolder: (folder) => ipcRenderer.invoke('library:remove-folder', folder),
  getState: () => ipcRenderer.invoke('library:get-state'),
  updateItem: (id, patch) => ipcRenderer.invoke('library:update-item', id, patch),
  renameCategory: (kind, oldName, newName) => ipcRenderer.invoke('library:rename-category', kind, oldName, newName),
  addCollection: (name) => ipcRenderer.invoke('library:add-collection', name),
  exportLibrary: () => ipcRenderer.invoke('library:export'),
  clearCache: () => ipcRenderer.invoke('app:clear-cache'),
  getCacheInfo: () => ipcRenderer.invoke('app:cache-info'),
  chooseCacheLocation: () => ipcRenderer.invoke('app:cache-location-choose'),
  getCachePolicy: () => ipcRenderer.invoke('app:cache-policy-get'),
  setCachePolicy: (days) => ipcRenderer.invoke('app:cache-policy-set', days),
  getWaveformCache: (key) => ipcRenderer.invoke('cache:get-waveform', key),
  setWaveformCache: (key, peaks) => ipcRenderer.invoke('cache:set-waveform', key, peaks),
  setTheme: (dark) => ipcRenderer.invoke('app:set-theme', dark),
  reveal: (path) => ipcRenderer.invoke('file:reveal', path),
  dragFile: (path, icon) => ipcRenderer.send('file:drag', path, icon),
  onDragError: (callback) => ipcRenderer.on('drag:error', (_, message) => callback(message)),
  onLibraryUpdated: (callback) => ipcRenderer.on('library:updated', (_, state) => callback(state)),
  onScanProgress: (callback) => ipcRenderer.on('scan:progress', (_, data) => callback(data))
});
